languageCode = "zh-cn"
languageName = "ç®€ä½“ä¸­æ–‡"
weight = 1
#title = "pyyy.xyz"

[params]
  displayName = "ä¸­æ–‡"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  description = "pyyy çš„ä¸ªäººç½‘ç«™"

[params.author]
  name = "pyyy"
  headline = """ğŸ‘¨ğŸ»â€ğŸ“@<a href="https://www.cqu.edu.cn" target="_blank" rel="noopener">é‡åº†å¤§å­¦</a><br>ğŸ‘¨ğŸ»â€ğŸ”§@<a href="https://mp.weixin.qq.com/s/B3HUb56MBZ4KYMGRqH00rQ" target="_blank" rel="noopener">FRC8214</a><br>ğŸ“·ğŸš´ğŸ¤–âœˆï¸"""

  image = "img/me.png"
  links = [
    { github = "https://github.com/peterpyyyyy" },
    { bilibili = "https://space.bilibili.com/357505609?spm_id_from=333.1007.0.0"},
    { strava = "https://www.strava.com/athletes/178275168" },
     { email = "mailto:superpyyy@qq.com" },
  ]
