languageCode = "en"
languageName = "English"
weight = 2

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  description = "pyyy's personal website"

[params.author]
  name = "pyyy"
  headline = """ğŸ‘¨ğŸ»â€ğŸ“@<a href="https://www.cqu.edu.cn" target="_blank" rel="noopener">Chongqing University</a><br>ğŸ‘¨ğŸ»â€ğŸ”§@<a href="https://mp.weixin.qq.com/s/B3HUb56MBZ4KYMGRqH00rQ" target="_blank" rel="noopener">FRC Team 8214</a><br><a>Mechanical Engineering</a><br>ğŸ“·ğŸš´ğŸ¤–âœˆï¸"""
  image = "img/me.png"
  links = [
    { github = "https://github.com/peterpyyyyy" },
    { bilibili = "https://space.bilibili.com/357505609?spm_id_from=333.1007.0.0" },
    { strava = "https://www.strava.com/athletes/your-id" },
    { email = "mailto:superpyyy@qq.com" }
  ]
