colorScheme = "Marvel"
defaultAppearance = "light"
autoSwitchAppearance = true
copyright = "{ year } @pyyy · <a href=\"https://beian.miit.gov.cn/\" target=\"_blank\" >粤ICP备2025494818号</a>"
enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

[header]
  layout = "fixed"

[homepage]
  layout = "myhome"
  homepageImage = "img/featured.svg"
  showRecent = false
  showRecentItems = 6

[article]
  showDate = true
  showAuthor = true
  showTableOfContents = true
  showReadingTime = true

[Author]
  name = "pyyy"
  image = "img/me.png"
  
[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showCards = true

[footer]
  showMenu = true
  showScrollToTop = true
  showAppearanceSwitcher = true
