colorScheme = "Marvel"
defaultAppearance = "light"
autoSwitchAppearance = true
copyright = "{ year } @pyyy"
enableSearch = true
enableCodeCopy = true
disableImageZoom = true
[records]
  [records.icp]
    number = "粤ICP备2025494818号"
    url = "https://beian.miit.gov.cn/"
  [records.publicSecurity]
    number = "粤公网安备44010602014311号"
    url = "https://beian.mps.gov.cn/#/query/webSearch?code=44010602014311"
    icon = "备案图标.png"

mainSections = ["posts"]

[header]
  layout = "fixed"

[homepage]
  layout = "myhome"
  homepageImage = "img/featured.svg"
  showRecent = false
  showRecentItems = 6

[article]
  showDate = true
  showAuthor = true
  showTableOfContents = true
  showReadingTime = true

[Author]
  name = "pyyy"
  image = "img/me.png"
  
[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showCards = true

[footer]
  showMenu = true
  showScrollToTop = true
  showAppearanceSwitcher = true
